name = enclave
description = A unified mod that combines defensive fences, concrete walls, hostile patrolling NPCs, and a modular base generator.
author = ronrob-lu
version = 1.0.0
depends = default, stairs, xpanes
